### ISSUE TITLE
Concern Regarding API Key

### ISSUE THREAD

**Issue by epikkoder** [neculaesei/devstream.tv#14]
I shared the link of this project on a Slack group, and one of the guys mentioned that he was thinking of doing something like this and asked Twitch devs about it. They said that as the application scaled, the API key would get throttled because of the API limits. I don't know if this is already in your mind, but I just want to throw this out there just in case that this ends up being something important.

**Comment by neculaesei** [comment]
Hey,
I thought about that, Twitch limits me at 120 API hits per minute, and currently we make a maximum of one API hit per second, which is half the limit. As streamers are added the sync time just takes longer, the app isn't hitting Twitch more often.
But it's really nice that you also thought about this issue.
Thank you!
