### ISSUE TITLE
Duplication of the stream

### ISSUE THREAD

**Issue by qWici** [neculaesei/devstream.tv#48]
Something wrong with list of streams. I check `streamers.json` and did not find duplication. Something with vue.

![2018-06-16 01-40-27](https://user-images.githubusercontent.com/11472929/41492219-5657221a-7106-11e8-9f32-53665ec403ab.png)

![2018-06-16 01-46-38](https://user-images.githubusercontent.com/11472929/41492328-24e82188-7107-11e8-8451-9ab7203551b7.png)

**Comment by neculaesei** [comment]
Fixed by @benrick
