### ISSUE TITLE
Local build instructions

### ISSUE THREAD

**Issue by ArunSahadeo** [neculaesei/devstream.tv#56]
Hey, thanks for adding my request to the latest build of the site, was wondering if you could also add build instructions, including package metadata files (such as package.json), in case anyone wants to build the site locally (I certainly would)

**Comment by neculaesei** [comment]
Hey, there is a frontend folder in the repo that holds the code for the frontend.
It's a regular Vue app, so just doing npm install and npm run dev should get you started :)

**Comment by ArunSahadeo** [comment]
Ah my bee the package.json file in the frontend code earlier.
Thanks, you can close this issue :)
